name: gemini_bloc
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # common
  page_transition: ^2.1.0
  lottie: ^2.7.0
  shake: ^2.2.0
  webview_flutter: ^4.8.0
  flutter_linkify: ^6.0.0
  flutter_parsed_text: ^2.2.1


  # network
  http: ^0.13.3
  http_interceptor: ^1.0.2
  dartz: ^0.10.1
  logger: ^1.1.0
  cached_network_image: ^3.3.1

  # db
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # file
  image_picker: ^1.1.1
  video_player: ^2.8.6

  # speech
  speech_to_text: ^6.6.1
  flutter_tts: ^4.0.2

  # bloc
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/videos/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf